# Apara aecssa a pagina
name: Atualizar Pagina Sistema

on: 
  schedule:
    - cron: '50 * * * *'
      
jobs:
  Acessando:
    runs-on: ubuntu-latest
    steps: 
      - name: Acessar página
        run: |
          curl -f -s -o /dev/null -w "%{http_code}" https://apihoteldosnobres.azurewebsites.net/actions | grep 200
 
