# Apara aecssa a pagina
name: Limpar Quartos do Hotel

on: 
  schedule:
    - cron: '0 17 * * *'
      
jobs:
  Acessando:
    runs-on: ubuntu-latest
    steps: 
      - name: Acessar pagina
        run: |
          curl -f -s -o /dev/null -w "%{http_code}" https://apihoteldosnobres.azurewebsites.net/actions?funcao=limparHotel | grep 200
 